#!/usr/bin/env python3
"""
Helper script to set up API keys for the promptlab project.
This script will create a .env file with your API keys.
"""

import os
import getpass

def setup_api_keys():
    """Interactive setup for API keys"""
    print("🔑 Setting up API keys for PromptLab")
    print("=" * 50)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/N): ").lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    # Collect API keys
    print("\nPlease provide your API keys:")
    print("(Press Enter to skip if you don't have a key for a particular service)")
    
    gemini_key = getpass.getpass("🔸 Gemini API Key: ").strip()
    openai_key = getpass.getpass("🔸 OpenAI API Key: ").strip()
    anthropic_key = getpass.getpass("🔸 Anthropic API Key: ").strip()
    deepseek_key = getpass.getpass("🔸 DeepSeek API Key: ").strip()
    
    # Write to .env file
    env_content = f"""# API Keys for LLM providers
# Generated by setup_api_keys.py

GEMINI_API_KEY={gemini_key}
OPENAI_API_KEY={openai_key}
ANTHROPIC_API_KEY={anthropic_key}
DEEPSEEK_API_KEY={deepseek_key}
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ API keys saved to .env file")
    print("🔒 The .env file is automatically ignored by git for security")
    
    # Show which services are configured
    configured = []
    if gemini_key:
        configured.append("Gemini")
    if openai_key:
        configured.append("OpenAI")
    if anthropic_key:
        configured.append("Anthropic")
    if deepseek_key:
        configured.append("DeepSeek")
    
    if configured:
        print(f"\n🎉 Configured services: {', '.join(configured)}")
    else:
        print("\n⚠️  No API keys were provided. Please add them manually to the .env file.")

if __name__ == "__main__":
    setup_api_keys() 